version: '3'
services:
  proxy:
    # platform: linux/x86_64 
    build:
      context: ./proxy
    container_name: ${APP_NAME}-proxy
    ports:
      - ${PROXY_PUBLIC_PORT}:80
      # SSLを使う場合はアンコメント
      # - ${PROXY_SSL_PORT}:443
    depends_on:
      - python
      - db
    volumes:
      - ./proxy/log/:/var/log/nginx/
      - ./proxy/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ${VOLUME_PATH}/:/var/www/html
      # SSLを使う場合はアンコメント
      # - ./proxy/ssl/:/etc/nginx/ssl/
    environment:
      APP_NAME: ${APP_NAME}
      PROJECT_NAME: ${PROJECT_NAME}
    # 環境変数を渡す
    command: /bin/sh -c "envsubst '$$PROJECT_NAME $$PROXY_SSL_PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  Phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${APP_NAME}-phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
    depends_on:
      - db
    ports:
      - ${PHP_MYADMIN_PUBLIC_PORT}:80
  db:
    # platform: 'linux/amd64'
    container_name: ${APP_NAME}-db
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./db/log:/var/log/mysql
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    expose:
      - "3306"
    tty: true
    environment:
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
  python:
    # platform: linux/x86_64 
    build:
      context: ./python
      args:
        PROJECT_NAME: ${PROJECT_NAME}
        USER: ${USER}
        PASSWORD: ${PASSWORD}
    container_name: ${APP_NAME}-python
    ports:
      - ${PYTHON_PORT}:8000
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - ${VOLUME_PATH}/:/home/${USER}
      # - ${VOLUME_PATH}/:/home/
    tty: true
    environment:
      PASSWORD: ${PASSWORD}
    working_dir: /home/${USER}
    command: /bin/bash -c "cd /home/${USER}/${PROJECT_NAME} && exec /bin/bash"
